# Generated by Django 4.0.4 on 2022-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tags',
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
